//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win7Cracks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win7Cracks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start? Make sure you have read all the notice because there are some important information there. We are not responsible for any damages done to your computer. Use it at your own risk.
        ///    
        ///You have been warned..
        /// </summary>
        internal static string ConfirmationText {
            get {
                return ResourceManager.GetString("ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///echo You are starting up in Setup mode. We&apos;re proccessing to reset trial period increase count...
        ///echo:
        ///echo Tweaking the registry...
        ///reg delete HKEY_LOCAL_MACHINE\WPA /f 2 &gt;nul 2&gt;&amp;1
        ///echo Done!
        ///echo:
        ///echo Disabling Setup mode...
        ///reg add HKLM\System\Setup /v SystemSetupInProgress /f /t REG_DWORD /d 0
        ///reg add HKLM\System\Setup /v SetupType /f /t REG_DWORD /d 0
        ///reg add HKLM\System\Setup /v CmdLine /f /t REG_SZ /d &quot;&quot;
        ///reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /f  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resettrial {
            get {
                return ResourceManager.GetString("resettrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\ul\b\f0\fs28\lang9 Windows 7 Activators collection\fs22\par
        ///\ulnone\b0 This is a small program that you can use to activate your Windows 7. This program includes programs that can help activating Windows 7. In this tool you can:\par
        ///1) Activate using Windows 7 Loader\par
        ///2) Activa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
    }
}
